# src/sab_core/schema/engine_response.py
from pydantic import BaseModel, Field
from typing import Any, List, Optional

class Response(BaseModel):
    """Standardized response model for SAB Engine execution."""
    result: Any = Field(
        None, 
        description="Raw execution result from the tool/executor."
        )

    content: str = Field(
        "", 
        description="Verbal response generated by the AI for the user."
        )

    suggestions: List[str] = Field(
        default_factory=list, 
        description="Follow-up action suggestions."
        )

    action_name: str = Field(
        ..., 
        description="The name of the action or tool executed."
        )