# engines/aiida/tools/submission/builder.py
from aiida.plugins import WorkflowFactory
from aiida.common.exceptions import MissingEntryPointError
from aiida.engine import submit
from aiida import orm

def inspect_workchain_spec(entry_point_name: str):
    """
    Inspect a WorkChain input spec and report required ports and protocol support.
    """
    try:
        WC = WorkflowFactory(entry_point_name)
    except MissingEntryPointError:
        return f"❌ Error: WorkChain '{entry_point_name}' not found."

    has_protocol = hasattr(WC, 'get_builder_from_protocol')
    spec = WC.spec()
    
    # Extract required inputs.
    required = [f"{k} ({v.valid_type.__name__ if v.valid_type else 'Any'})" 
                for k, v in spec.inputs.items() if v.required]
    
    summary = (
        f"**WorkChain:** `{entry_point_name}`\n"
        f"**Supports Protocols:** {'✅ YES' if has_protocol else '❌ NO'}\n"
        f"**Required Inputs:** {', '.join(required) if required else 'None'}"
    )
    return summary

def draft_workchain_builder(workchain_label: str, structure_pk: int, code_label: str, protocol: str = 'moderate', overrides: dict = None):
    """
    Draft a WorkChain builder from protocol without submitting it.
    Returns a confirmation-ready draft payload.
    """
    try:
        # 1. Validate resources.
        WC = WorkflowFactory(workchain_label)
        if not hasattr(WC, 'get_builder_from_protocol'):
            return "❌ Error: This WorkChain does not support protocols."

        # 2. Dry-run builder construction to validate parameters.
        _ = WC.get_builder_from_protocol(
            code=orm.load_code(code_label),
            structure=orm.load_node(structure_pk),
            protocol=protocol,
            overrides=overrides or {}
        )

        # 3. Return structured payload for AI/UI confirmation.
        return {
            "status": "DRAFT_READY",
            "workchain": workchain_label,
            "structure_pk": structure_pk,
            "code": code_label,
            "protocol": protocol,
            "overrides": overrides or {},
            "preview": f"Ready to submit {workchain_label} using {protocol} protocol."
        }
        
    except Exception as e:
        return f"❌ Builder Draft Failed: {str(e)}"

def submit_workchain_builder(draft_data: dict):
    """
    Submit a WorkChain from draft payload generated by `draft_workchain_builder`.
    """
    try:
        # Read all required values from the draft payload.
        wc_name = draft_data.get('workchain')
        struct_pk = draft_data.get('structure_pk')
        code_label = draft_data.get('code')
        protocol = draft_data.get('protocol', 'moderate')
        overrides = draft_data.get('overrides', {})

        # Reload AiiDA resources and submit.
        WorkChain = WorkflowFactory(wc_name)
        builder = WorkChain.get_builder_from_protocol(
            code=orm.load_code(code_label),
            structure=orm.load_node(struct_pk),
            protocol=protocol,
            overrides=overrides
        )
        
        node = submit(builder)
        return f"✅ Success! WorkChain submitted. PK: {node.pk}"
        
    except Exception as e:
        return f"❌ Submission failed: {str(e)}"
