presets:
  "*ucl.ac.be":
    description: "UCLouvain Tier-1 supercomputer Lucia"
    transport_type: "core.ssh"
    scheduler_type: "core.slurm"
    work_dir: "/scratch/users/{username}/aiida/"
    mpiprocs_per_machine: 112
    mpirun_command: "srun -n {tot_num_mpiprocs}"
    prepend_text: |
      module purge
      module load intel/2023a
    use_login_shell: true
    safe_interval: 10.0
    connection_timeout: 60
    codes:
      - label: "pw"
        default_calc_job_plugin: "quantumespresso.pw"
        remote_abspath: "/softs/EB/software/QuantumESPRESSO/7.2-intel-2023a/bin/pw.x"
      - label: "ph"
        default_calc_job_plugin: "quantumespresso.ph"
        remote_abspath: "/softs/EB/software/QuantumESPRESSO/7.2-intel-2023a/bin/ph.x"

  "*.harvard.edu":
    description: "FASRC Cannon Cluster (Harvard)"
    transport_type: "core.ssh"
    scheduler_type: "core.slurm"
    work_dir: "/n/holyscratch01/{username}/aiida/"
    mpiprocs_per_machine: 64
    mpirun_command: "srun -n {tot_num_mpiprocs} --mpi=pmix"
    prepend_text: |
      module load intel/23.0.0-fasrc01
    use_login_shell: true
    safe_interval: 5.0
    connection_timeout: 60
    codes:
      - label: "pw"
        default_calc_job_plugin: "quantumespresso.pw"
        remote_abspath: "/n/sw/eb/apps/centos7/QuantumESPRESSO/7.2-intel-2023a/bin/pw.x"
